source 'https://rubygems.org'
ruby '2.4.1'

gem 'hanami',       '~> 1.2'
gem 'hanami-model', '~> 1.2'
gem 'pg'
gem 'rake'

group :development do
  # Code reloading
  # See: http://hanamirb.org/guides/projects/code-reloading
  gem 'hanami-webconsole'
  gem 'pry'
  gem 'shotgun', platforms: :ruby
end

group :test, :development do
  gem 'dotenv', '~> 2.0'
end

group :test do
  gem 'capybara'
  gem 'puma'
  gem 'rspec'
  gem 'selenium-webdriver'
end

group :production do
  # gem 'puma'
end
